import React from 'react';
import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import { Backdrop, CircularProgress, Box, Stack } from '@mui/material';
import * as cookie from '../../libs/cookie';
import styles from '../../styles/Connect.module.css';

const Databases: NextPage = () => {
  const [uri, setUri] = React.useState<string>('');
  const [loading, setLoading] = React.useState<boolean>(false);
  const [databaseInfo, setDatabaseInfo] = React.useState<any>(null);
  const router = useRouter();

  React.useEffect(() => {
    if(!cookie.check('CONNECTION-URI')) {
      router.replace('/connect');
    }

    setUri(cookie.get('CONNECTION-URI'));
  }, []);

  React.useEffect(() => {
    if(uri.length) {
      requestDatabaseList();
    }
  }, [uri]);

  const requestDatabaseList = async () => {
    setLoading(true);

    try {
      const res = await fetch('/api/databases', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ uri }),
      });

      if(res.status === 200) {
        const data = await res.json();

        setDatabaseInfo(data.databases);
      }
    } catch (err) {
      router.replace('/connect');
    } finally {
      setLoading(false);
    }
  };

  const Databases = databaseInfo?.databases?.map((item: any, index: number) => {
    return (
      <Stack key={index} spacing={4} direction="row">
        <Box>{item.name}</Box>
        <Box>{item.sizeOnDisk}</Box>
        <Box>{item.empty}</Box>
      </Stack>
    );
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Stack>
          <Box>
            {uri}
          </Box>
          {Databases}
        </Stack>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

      <Backdrop
        open={loading}
        sx={{ color: '#FFFFFF' }}>
        <CircularProgress color="inherit" />
      </Backdrop>
    </div>
  );
};

export default Databases;
